/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CsvExportListRelationFilter } from "../../csvExport/base/CsvExportListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { ReportListRelationFilter } from "../../report/base/ReportListRelationFilter";
import { TradeSettingsListRelationFilter } from "../../tradeSettings/base/TradeSettingsListRelationFilter";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { WalletListRelationFilter } from "../../wallet/base/WalletListRelationFilter";

@InputType()
class UserWhereInput {
  @ApiProperty({
    required: false,
    type: () => CsvExportListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CsvExportListRelationFilter)
  @IsOptional()
  @Field(() => CsvExportListRelationFilter, {
    nullable: true,
  })
  csvExports?: CsvExportListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  email?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  firstName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  lastName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ReportListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ReportListRelationFilter)
  @IsOptional()
  @Field(() => ReportListRelationFilter, {
    nullable: true,
  })
  reports?: ReportListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  telegramId?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => TradeSettingsListRelationFilter,
  })
  @ValidateNested()
  @Type(() => TradeSettingsListRelationFilter)
  @IsOptional()
  @Field(() => TradeSettingsListRelationFilter, {
    nullable: true,
  })
  tradeSettingsItems?: TradeSettingsListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  username?: StringFilter;

  @ApiProperty({
    required: false,
    type: FloatNullableFilter,
  })
  @Type(() => FloatNullableFilter)
  @IsOptional()
  @Field(() => FloatNullableFilter, {
    nullable: true,
  })
  walletBalance?: FloatNullableFilter;

  @ApiProperty({
    required: false,
    type: () => WalletListRelationFilter,
  })
  @ValidateNested()
  @Type(() => WalletListRelationFilter)
  @IsOptional()
  @Field(() => WalletListRelationFilter, {
    nullable: true,
  })
  wallets?: WalletListRelationFilter;
}

export { UserWhereInput as UserWhereInput };
