/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CsvExportUpdateManyWithoutUsersInput } from "./CsvExportUpdateManyWithoutUsersInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsNumber,
  Min,
  Max,
} from "class-validator";
import { Type } from "class-transformer";
import { ReportUpdateManyWithoutUsersInput } from "./ReportUpdateManyWithoutUsersInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { TradeSettingsUpdateManyWithoutUsersInput } from "./TradeSettingsUpdateManyWithoutUsersInput";
import { WalletUpdateManyWithoutUsersInput } from "./WalletUpdateManyWithoutUsersInput";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: () => CsvExportUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => CsvExportUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => CsvExportUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  csvExports?: CsvExportUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
    type: () => ReportUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ReportUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ReportUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  reports?: ReportUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  roles?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  telegramId?: string | null;

  @ApiProperty({
    required: false,
    type: () => TradeSettingsUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => TradeSettingsUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => TradeSettingsUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  tradeSettingsItems?: TradeSettingsUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  walletBalance?: number | null;

  @ApiProperty({
    required: false,
    type: () => WalletUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => WalletUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => WalletUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  wallets?: WalletUpdateManyWithoutUsersInput;
}

export { UserUpdateInput as UserUpdateInput };
