/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { WalletService } from "../wallet.service";
import { WalletCreateInput } from "./WalletCreateInput";
import { Wallet } from "./Wallet";
import { WalletFindManyArgs } from "./WalletFindManyArgs";
import { WalletWhereUniqueInput } from "./WalletWhereUniqueInput";
import { WalletUpdateInput } from "./WalletUpdateInput";
import { CsvExportFindManyArgs } from "../../csvExport/base/CsvExportFindManyArgs";
import { CsvExport } from "../../csvExport/base/CsvExport";
import { CsvExportWhereUniqueInput } from "../../csvExport/base/CsvExportWhereUniqueInput";
import { TradeOrderFindManyArgs } from "../../tradeOrder/base/TradeOrderFindManyArgs";
import { TradeOrder } from "../../tradeOrder/base/TradeOrder";
import { TradeOrderWhereUniqueInput } from "../../tradeOrder/base/TradeOrderWhereUniqueInput";

export class WalletControllerBase {
  constructor(protected readonly service: WalletService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Wallet })
  async createWallet(@common.Body() data: WalletCreateInput): Promise<Wallet> {
    return await this.service.createWallet({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        privateKey: true,
        publicKey: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Wallet] })
  @ApiNestedQuery(WalletFindManyArgs)
  async wallets(@common.Req() request: Request): Promise<Wallet[]> {
    const args = plainToClass(WalletFindManyArgs, request.query);
    return this.service.wallets({
      ...args,
      select: {
        createdAt: true,
        id: true,
        privateKey: true,
        publicKey: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Wallet })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async wallet(
    @common.Param() params: WalletWhereUniqueInput
  ): Promise<Wallet | null> {
    const result = await this.service.wallet({
      where: params,
      select: {
        createdAt: true,
        id: true,
        privateKey: true,
        publicKey: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Wallet })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateWallet(
    @common.Param() params: WalletWhereUniqueInput,
    @common.Body() data: WalletUpdateInput
  ): Promise<Wallet | null> {
    try {
      return await this.service.updateWallet({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          privateKey: true,
          publicKey: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Wallet })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteWallet(
    @common.Param() params: WalletWhereUniqueInput
  ): Promise<Wallet | null> {
    try {
      return await this.service.deleteWallet({
        where: params,
        select: {
          createdAt: true,
          id: true,
          privateKey: true,
          publicKey: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/csvExports")
  @ApiNestedQuery(CsvExportFindManyArgs)
  async findCsvExports(
    @common.Req() request: Request,
    @common.Param() params: WalletWhereUniqueInput
  ): Promise<CsvExport[]> {
    const query = plainToClass(CsvExportFindManyArgs, request.query);
    const results = await this.service.findCsvExports(params.id, {
      ...query,
      select: {
        createdAt: true,
        generatedAt: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        wallet: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/csvExports")
  async connectCsvExports(
    @common.Param() params: WalletWhereUniqueInput,
    @common.Body() body: CsvExportWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      csvExports: {
        connect: body,
      },
    };
    await this.service.updateWallet({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/csvExports")
  async updateCsvExports(
    @common.Param() params: WalletWhereUniqueInput,
    @common.Body() body: CsvExportWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      csvExports: {
        set: body,
      },
    };
    await this.service.updateWallet({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/csvExports")
  async disconnectCsvExports(
    @common.Param() params: WalletWhereUniqueInput,
    @common.Body() body: CsvExportWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      csvExports: {
        disconnect: body,
      },
    };
    await this.service.updateWallet({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/tradeOrders")
  @ApiNestedQuery(TradeOrderFindManyArgs)
  async findTradeOrders(
    @common.Req() request: Request,
    @common.Param() params: WalletWhereUniqueInput
  ): Promise<TradeOrder[]> {
    const query = plainToClass(TradeOrderFindManyArgs, request.query);
    const results = await this.service.findTradeOrders(params.id, {
      ...query,
      select: {
        amount: true,
        createdAt: true,
        id: true,
        jitoFee: true,
        price: true,
        priorityFee: true,
        slippage: true,
        status: true,

        token: {
          select: {
            id: true,
          },
        },

        typeField: true,
        updatedAt: true,

        wallet: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/tradeOrders")
  async connectTradeOrders(
    @common.Param() params: WalletWhereUniqueInput,
    @common.Body() body: TradeOrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tradeOrders: {
        connect: body,
      },
    };
    await this.service.updateWallet({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/tradeOrders")
  async updateTradeOrders(
    @common.Param() params: WalletWhereUniqueInput,
    @common.Body() body: TradeOrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tradeOrders: {
        set: body,
      },
    };
    await this.service.updateWallet({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/tradeOrders")
  async disconnectTradeOrders(
    @common.Param() params: WalletWhereUniqueInput,
    @common.Body() body: TradeOrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tradeOrders: {
        disconnect: body,
      },
    };
    await this.service.updateWallet({
      where: params,
      data,
      select: { id: true },
    });
  }
}
