/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CsvExportListRelationFilter } from "../../csvExport/base/CsvExportListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { StringFilter } from "../../util/StringFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { TradeOrderListRelationFilter } from "../../tradeOrder/base/TradeOrderListRelationFilter";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class WalletWhereInput {
  @ApiProperty({
    required: false,
    type: () => CsvExportListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CsvExportListRelationFilter)
  @IsOptional()
  @Field(() => CsvExportListRelationFilter, {
    nullable: true,
  })
  csvExports?: CsvExportListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  privateKey?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  publicKey?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => TradeOrderListRelationFilter,
  })
  @ValidateNested()
  @Type(() => TradeOrderListRelationFilter)
  @IsOptional()
  @Field(() => TradeOrderListRelationFilter, {
    nullable: true,
  })
  tradeOrders?: TradeOrderListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput;
}

export { WalletWhereInput as WalletWhereInput };
