/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TokenService } from "../token.service";
import { TokenCreateInput } from "./TokenCreateInput";
import { Token } from "./Token";
import { TokenFindManyArgs } from "./TokenFindManyArgs";
import { TokenWhereUniqueInput } from "./TokenWhereUniqueInput";
import { TokenUpdateInput } from "./TokenUpdateInput";
import { TradeOrderFindManyArgs } from "../../tradeOrder/base/TradeOrderFindManyArgs";
import { TradeOrder } from "../../tradeOrder/base/TradeOrder";
import { TradeOrderWhereUniqueInput } from "../../tradeOrder/base/TradeOrderWhereUniqueInput";

export class TokenControllerBase {
  constructor(protected readonly service: TokenService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Token })
  async createToken(@common.Body() data: TokenCreateInput): Promise<Token> {
    return await this.service.createToken({
      data: data,
      select: {
        createdAt: true,
        decimals: true,
        id: true,
        name: true,
        symbolField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Token] })
  @ApiNestedQuery(TokenFindManyArgs)
  async tokens(@common.Req() request: Request): Promise<Token[]> {
    const args = plainToClass(TokenFindManyArgs, request.query);
    return this.service.tokens({
      ...args,
      select: {
        createdAt: true,
        decimals: true,
        id: true,
        name: true,
        symbolField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Token })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async token(
    @common.Param() params: TokenWhereUniqueInput
  ): Promise<Token | null> {
    const result = await this.service.token({
      where: params,
      select: {
        createdAt: true,
        decimals: true,
        id: true,
        name: true,
        symbolField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Token })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateToken(
    @common.Param() params: TokenWhereUniqueInput,
    @common.Body() data: TokenUpdateInput
  ): Promise<Token | null> {
    try {
      return await this.service.updateToken({
        where: params,
        data: data,
        select: {
          createdAt: true,
          decimals: true,
          id: true,
          name: true,
          symbolField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Token })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteToken(
    @common.Param() params: TokenWhereUniqueInput
  ): Promise<Token | null> {
    try {
      return await this.service.deleteToken({
        where: params,
        select: {
          createdAt: true,
          decimals: true,
          id: true,
          name: true,
          symbolField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/tradeOrders")
  @ApiNestedQuery(TradeOrderFindManyArgs)
  async findTradeOrders(
    @common.Req() request: Request,
    @common.Param() params: TokenWhereUniqueInput
  ): Promise<TradeOrder[]> {
    const query = plainToClass(TradeOrderFindManyArgs, request.query);
    const results = await this.service.findTradeOrders(params.id, {
      ...query,
      select: {
        amount: true,
        createdAt: true,
        id: true,
        jitoFee: true,
        price: true,
        priorityFee: true,
        slippage: true,
        status: true,

        token: {
          select: {
            id: true,
          },
        },

        typeField: true,
        updatedAt: true,

        wallet: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/tradeOrders")
  async connectTradeOrders(
    @common.Param() params: TokenWhereUniqueInput,
    @common.Body() body: TradeOrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tradeOrders: {
        connect: body,
      },
    };
    await this.service.updateToken({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/tradeOrders")
  async updateTradeOrders(
    @common.Param() params: TokenWhereUniqueInput,
    @common.Body() body: TradeOrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tradeOrders: {
        set: body,
      },
    };
    await this.service.updateToken({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/tradeOrders")
  async disconnectTradeOrders(
    @common.Param() params: TokenWhereUniqueInput,
    @common.Body() body: TradeOrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tradeOrders: {
        disconnect: body,
      },
    };
    await this.service.updateToken({
      where: params,
      data,
      select: { id: true },
    });
  }
}
